// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { FlashDAOFactory$Type } from "./FlashDAOFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FlashDAOFactory"]: FlashDAOFactory$Type;
    ["contracts/FlashDAOFactory.sol:FlashDAOFactory"]: FlashDAOFactory$Type;
  }
}
