// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { FlashDAOAgent$Type } from "./FlashDAOAgent";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FlashDAOAgent"]: FlashDAOAgent$Type;
    ["contracts/FlashDAOAgent.sol:FlashDAOAgent"]: FlashDAOAgent$Type;
  }
}
