// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { FlashDAORewards$Type } from "./FlashDAORewards";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FlashDAORewards"]: FlashDAORewards$Type;
    ["contracts/FlashDAORewards.sol:FlashDAORewards"]: FlashDAORewards$Type;
  }
}
