// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721Utils$Type } from "./ERC721Utils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Utils"]: ERC721Utils$Type;
    ["@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils"]: ERC721Utils$Type;
  }
}
