// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { FlashDAO$Type } from "./FlashDAO";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FlashDAO"]: FlashDAO$Type;
    ["contracts/FlashDAO.sol:FlashDAO"]: FlashDAO$Type;
  }
}
